### ISSUE TITLE
--size isn't handled by argparse?

### ISSUE THREAD

**Issue by luckman212** [m-radzikowski/icons-asset-generator#3]
very useful project! 🙏 

I wanted to use the `--size` parameter, but it isn't accepted by the [parser](https://github.com/m-radzikowski/icons-asset-generator/blob/master/icons_asset_generator/arguments.py).

(I tried `--size longest=100` for example)

**Comment by m-radzikowski** [comment]
Hey,
the `--size` parameter is accepted only for `diagrams.net` and must be specified after the `diagrams.net` subcommand ([source](https://github.com/m-radzikowski/icons-asset-generator/blob/dd0ed3eaceefb9c6ecddbf54c9c5c348af85f166/icons_asset_generator/diagramsnet/diagramsnet.py#L34)):

```
poetry run icons-asset-generator \
    --path ./icons \
    diagrams.net \
    --size longest=100
```

Hope this helps!

**Comment by luckman212** [comment]
Ah, yes that definitely helps! Sorry I missed that.
